### ISSUE TITLE
Argument of type 'ValidationError' is not assignable to parameter of type 'ZodError'.

### ISSUE THREAD

**Issue by kevinswarner** [causaly/zod-validation-error#207] opened 2023-12-29 22:07 UTC
I am trying to use this library to get a nicely formatted Zod error. But, I get the following Typescript error when attempting to use fromZodError(error).

Argument of type 'ValidationError' is not assignable to parameter of type 'ZodError'. Type 'ValidationError' is missing the following properties from type 'ZodError<any>': issues, errors, format, isEmpty, and 4 more.

```typescript
import { z } from 'zod';
import { fromZodError, isValidationErrorLike } from 'zod-validation-error';

const schema = z.object({
  foo: z.string()
});

try {
  schema.parse({
    foo: 'bar'
  });
  console.log('ok');

  // Do something else...

  // Maybe throw a standard error...

} catch (error) {
  if (isValidationErrorLike(error)) {
    console.log(fromZodError(error)); // ERROR IS OCCURRING HERE
  }
  // Maybe handle standard error in a different way...
}
```

I appreciate any help or direction you can provide.

**Comment by thanoskrg** [comment] 2024-01-03 08:42
Hi @kevinswarner , thanks for reporting this. Can you please provide the version of the library you have installed?

**Comment by kevinswarner** [comment] 2024-01-03 14:24
2.1.0. I may be using that method incorrectly. I am currently doing this...

```
try {
// Do something
} catch (error) {
  const message =
    error instanceof ZodError
      ? fromZodError(error).message
      : getErrorMessage(error);

    // Do something here...
}
```
I was under the initial impression that isValidationErrorLike was meant to check if it was a ZodError, but after looking a little more, maybe it is meant to determine if a "ValidationError" from your library was thrown specifically, and not a ZodError.

Thanks for the attention.

**Comment by thanoskrg** [comment] 2024-01-04 06:56
@jmike not sure whether this is a bug. Your input here would be great. After taking a better look at this, I am under the impression that `fromZodError` isn't meant to handle `ValidationError` instances. 

In fact, according to the [docs](https://github.com/causaly/zod-validation-error?tab=readme-ov-file#fromzoderror), it converts a `ZodError` to `ValidationError`. 

So having said that, @kevinswarner I think your `error instanceof ZodError` ternary expression inside the catch-block is the way to go here.

**Comment by thanoskrg** [comment] 2024-01-04 07:00
Also, @kevinswarner do you agree that this is duplicate of #42 ? Maybe we can move the discussion there.

**Comment by kevinswarner** [comment] 2024-01-04 16:12
I am not sure if it is the same as #42, but I think this issue can be closed as I was confused about how the library works. Thank you.

**Comment by jmike** [comment] 2024-02-12 08:35
Closing this issue per author's recommendation (see above).

**Closed by jmike** 2024-02-12 08:35 UTC
